spring.application.name=gps-registration-service

server.port=8083

app.kafka.topics.kafka-topic=gps-locations
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.acks=1
spring.kafka.producer.batch-size=32768
spring.kafka.producer.compression-type=lz4
spring.kafka.producer.retries=2147483647


