spring.application.name=gps-service

server.port=8084

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.generate_statistics=true


#kafka topic
kafka.topics.locations=gps-locations
kafka.consumer.group-id=gps-service
spring.kafka.listener.type=single

#service
app.device.service=http://localhost:8082/api/v1/devices