spring.application.name=device-service
server.port=8082

#kafka topic
kafka.topics.device=device-registered
kafka.consumer.group-id=device-service
spring.kafka.listener.type=batch


# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.generate_statistics=true


